CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE data_protection_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    friendly_name text NULL,
    xml text NULL,
    CONSTRAINT pk_data_protection_keys PRIMARY KEY (id)
);

CREATE TABLE inspire_roles (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(256) NULL,
    normalized_name character varying(256) NULL,
    concurrency_stamp text NULL,
    CONSTRAINT pk_inspire_roles PRIMARY KEY (id)
);

CREATE TABLE inspire_users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NULL,
    last_name text NULL,
    street text NULL,
    city text NULL,
    state text NULL,
    country text NULL,
    zip_code text NULL,
    user_theme text NULL,
    profile_image text NULL,
    confirm_email_code text NULL,
    reset_password_code text NULL,
    is_active boolean NOT NULL,
    user_name character varying(256) NULL,
    normalized_user_name character varying(256) NULL,
    email character varying(256) NULL,
    normalized_email character varying(256) NULL,
    email_confirmed boolean NOT NULL,
    password_hash text NULL,
    security_stamp text NULL,
    concurrency_stamp text NULL,
    phone_number text NULL,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone NULL,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_inspire_users PRIMARY KEY (id)
);

CREATE TABLE inspire_role_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id integer NOT NULL,
    claim_type text NULL,
    claim_value text NULL,
    CONSTRAINT pk_inspire_role_claims PRIMARY KEY (id),
    CONSTRAINT "FK_inspire_role_claims_inspire_roles_role_id" FOREIGN KEY (role_id) REFERENCES inspire_roles (id) ON DELETE CASCADE
);

CREATE TABLE inspire_user_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    claim_type text NULL,
    claim_value text NULL,
    CONSTRAINT pk_inspire_user_claims PRIMARY KEY (id),
    CONSTRAINT "FK_inspire_user_claims_inspire_users_user_id" FOREIGN KEY (user_id) REFERENCES inspire_users (id) ON DELETE CASCADE
);

CREATE TABLE inspire_user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text NULL,
    user_id integer NOT NULL,
    CONSTRAINT pk_inspire_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT "FK_inspire_user_logins_inspire_users_user_id" FOREIGN KEY (user_id) REFERENCES inspire_users (id) ON DELETE CASCADE
);

CREATE TABLE inspire_user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT pk_inspire_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT "FK_inspire_user_roles_inspire_roles_role_id" FOREIGN KEY (role_id) REFERENCES inspire_roles (id) ON DELETE CASCADE,
    CONSTRAINT "FK_inspire_user_roles_inspire_users_user_id" FOREIGN KEY (user_id) REFERENCES inspire_users (id) ON DELETE CASCADE
);

CREATE TABLE inspire_user_tokens (
    user_id integer NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text NULL,
    CONSTRAINT pk_inspire_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT "FK_inspire_user_tokens_inspire_users_user_id" FOREIGN KEY (user_id) REFERENCES inspire_users (id) ON DELETE CASCADE
);

CREATE INDEX ix_inspire_role_claims_role_id ON inspire_role_claims (role_id);

CREATE UNIQUE INDEX role_name_index ON inspire_roles (normalized_name);

CREATE INDEX ix_inspire_user_claims_user_id ON inspire_user_claims (user_id);

CREATE INDEX ix_inspire_user_logins_user_id ON inspire_user_logins (user_id);

CREATE INDEX ix_inspire_user_roles_role_id ON inspire_user_roles (role_id);

CREATE INDEX email_index ON inspire_users (normalized_email);

CREATE UNIQUE INDEX user_name_index ON inspire_users (normalized_user_name);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211231123353_InitialCreate', '6.0.1');

COMMIT;

